CREATE DATABASE Budgetplanner;

USE Budgetplanner;

CREATE TABLE USER(
Id Int PRIMARY KEY AUTO_INCREMENT,
Username VARCHAR(100),
EMail VARCHAR(250) UNIQUE NOT NULL,
Passwort VARCHAR(250) NOT Null
);

CREATE TABLE Budget(
Id Int PRIMARY KEY AUTO_INCREMENT,
UserFID INT,
Monthly_Limit DOUBLE(10,2),
FOREIGN KEY (UserFID) REFERENCES USER(Id)
);


CREATE TABLE Category(
Id Int PRIMARY KEY AUTO_INCREMENT,
Name VARCHAR(200)
);


CREATE TABLE Transactions (
Id Int PRIMARY KEY AUTO_INCREMENT,
UserFID INT,
Amount DOUBLE(10,2) NOT Null,
Description VARCHAR(300),
Date DATE DEFAULT CURRENT_DATE(),
Typ ENUM('Einahme', 'Ausgabe'),
CategoryFID INT,
FOREIGN KEY (UserFID) REFERENCES USER(Id),
FOREIGN KEY (CategoryFID) REFERENCES Category(Id)
);