services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: budgetplaner_db
    ports:
      - "3306:3306"
    networks:
      - mariadb_network

networks:
  mariadb_network:
    driver: bridge